name: Dump

on:
  workflow_dispatch:
    inputs:
      urls:
        description: 'URLs'
        default: 'https://bn.d.miui.com/OS1.0.2.0.TGCINXM/miui_SPESINGlobal_OS1.0.2.0.TGCINXM_f57d472765_13.0.zip'
        required: true

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-codeql: true
          remove-haskell: true
          remove-docker-images: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .githubtoken file
        run: echo "${{ secrets.GIT_TOKEN }}" > .githubtoken

      # - name: Create .tgtoken file
      #   run: echo "${{ secrets.TELEGRAM_TOKEN }}" > .tgtoken

      - name: Set up environment
        run: bash setup.sh

      - name: Run dumpyara
        run: |
          bash dumpyara.sh ${{ inputs.urls }}
